steps:
- name: gcr.io/cloud-builders/docker
  args: ['build', '--network=cloudbuild', '-t', 'gcr.io/$PROJECT_ID/tamuhackers19:$COMMIT_SHA', '.']


- name: gcr.io/cloud-builders/kubectl
  args: ['set', 'image', 'deployments/tamuhackers19', 'tamuhackers19=gcr.io/$PROJECT_ID/tamuhackers19:$COMMIT_SHA']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=tamuhackers19'
images: 
- 'gcr.io/$PROJECT_ID/tamuhackers19:$COMMIT_SHA'